# Generated by Django 5.2.5 on 2025-08-31 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_carrinho'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrinho',
            old_name='id_produto',
            new_name='Produto',
        ),
    ]
