# Generated by Django 5.2.5 on 2025-08-31 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_rename_id_produto_carrinho_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
