# Generated by Django 5.2.5 on 2025-09-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_alter_carrinho_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
